# Generated by Django 4.2.9 on 2025-01-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_users'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='project_start_date_lte_end_date',
        ),
        migrations.RemoveConstraint(
            model_name='project',
            name='project_end_date_gte_start_date',
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lte', models.F('end_date'))), name='project_start_date_lte_end_date', violation_error_message='Start date must be less than or equal to end date.'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='project_end_date_gte_start_date', violation_error_message='End date must be greater than or equal to start date.'),
        ),
    ]
