services:
  taskmanager:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver
    env_file:
      - taskmanager/taskmanager/.env
    depends_on:
      - postgresql
      - taskmanager-redis

  postgresql:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - taskmanager/taskmanager/.env

  taskmanager-redis:
    image: redis:latest
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - nginx_config:/etc/nginx/conf.d
    depends_on:
      - taskmanager

volumes:
  postgres_data:
  nginx_config:
