services:
  taskmanager:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py test --keepdb
    env_file:
      - taskmanager/taskmanager/.env
    depends_on:
      - postgresql
      - taskmanager-redis

  postgresql:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - taskmanager/taskmanager/.env

  taskmanager-redis:
    image: redis:latest

volumes:
  postgres_data: