services:
  taskmanager:
    image: python:3.8-slim-buster
    volumes:
      - ./taskmanager:/usr/src/app
      - ./requirements.txt:/requirements.txt
    command: bash -c "pip install -r /requirements.txt && python /usr/src/app/manage.py makemigrations && python /usr/src/app/manage.py migrate && python usr/src/app/manage.py collectstatic --noinput && python /usr/src/app/manage.py runserver 0.0.0.0:8000"
    env_file:
      - taskmanager/taskmanager/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
      - taskmanager-redis

  postgresql:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - taskmanager/taskmanager/.env

  taskmanager-redis:
    image: redis:latest
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - nginx_config:/etc/nginx/conf.d
    depends_on:
      - taskmanager

volumes:
  postgres_data:
  nginx_config: