services:
  postgresql:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - taskmanager/taskmanager/.env
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  taskmanager-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - nginx_config:/etc/nginx/conf.d
      - /home/berkay/task-manager-api/taskmanager/media:/home/berkay/task-manager-api/taskmanager/media
      - /home/berkay/task-manager-api/taskmanager/static:/home/berkay/task-manager-api/taskmanager/static
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  postgres_data:
  nginx_config: