# Generated by Django 4.2.7 on 2024-04-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='start_date_lte_end_date',
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='end_date_gte_start_date',
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lte', models.F('end_date'))), name='task_start_date_lte_end_date'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='task_end_date_gte_start_date'),
        ),
    ]
