# Generated by Django 4.2.7 on 2024-04-13 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_users'),
        ('tasks', '0006_remove_task_start_date_lte_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project'),
            preserve_default=False,
        ),
    ]
