# Generated by Django 4.2.7 on 2024-07-11 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_comment_creator_alter_mention_mentioned_user'),
        ('projects', '0005_alter_project_users'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to='tasks.task'),
        ),
    ]
