# Generated by Django 4.2.9 on 2025-01-26 09:46

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_sharedfile_project_alter_sharedfile_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfile',
            name='file',
            field=models.FileField(upload_to='shared_files/', validators=[files.models.validate_file_extension_and_content, files.models.validate_file_size]),
        ),
    ]
