name: ci
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: 'taskmanager.settings.local'
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    services:
      redis:
        image: 'redis:6'
        ports:
          - '6379:6379'
        options: >-
          --health-cmd "redis-cli ping" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Start PostgreSQL
        run: |
          pwd
          sudo systemctl start postgresql.service
      - name: Set up PostgreSQL user password
        run: |
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"
      - name: Set environment variables for PostgreSQL and Redis
        run: |
          echo "POSTGRES_DB=postgres" >> $GITHUB_ENV
          echo "POSTGRES_USER=postgres" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=postgres" >> $GITHUB_ENV  # Leave empty or specify a password if needed
          echo "POSTGRES_HOST=localhost" >> $GITHUB_ENV
          echo "POSTGRES_PORT=5432" >> $GITHUB_ENV
          echo "REDIS_URL=redis://localhost:6379/0" >> $GITHUB_ENV
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: '${{ runner.os }}-pip-${{ hashFiles(''**/requirements.txt'') }}'
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pwd
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Redis CLI
        run: sudo apt-get install -y redis-tools
      - name: Wait for PostgreSQL
        run: |
          timeout 60s bash -c 'until pg_isready -h localhost -p 5432; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done'
      - name: Wait for Redis
        run: |
          timeout 60s bash -c 'until redis-cli -h localhost ping; do
            echo "Waiting for Redis..."
            sleep 2
          done'
      - name: Run Migrations
        working-directory: taskmanager
        run: |
          pwd
          python manage.py migrate
      - name: Run Unit Tests
        working-directory: taskmanager
        run: |
          pwd
          python manage.py test
  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: >-
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name
            }}:latest
